config/routes.rb
Rails.application.routes.draw do

  root 'home#dashboard'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :products
  resources :commissions
  resources :regions
  resources :sales
  resources :clients

  get 'ranking'  => 'static_pages#ranking'
  get 'dashboard'  => 'home#dashboard'
  
  get '*path' => redirect('/')
  

  get '/rails/info/properties' => "rails/info#properties"
  get '/rails/info/routes'     => "rails/info#routes"
  get '/rails/info'            => "rails/info#index"
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	#validates :product_id, presence: true
	validates :quantity, :numericality => { :greater_than => 0 }

	belongs_to :user
	belongs_to :client

  	has_one :product
	  
	accepts_nested_attributes_for :product
	
  	after_initialize :init
	before_save :calculate

    def init
	    self.quantity		||= 0.0  
	    self.tax			||= 0.0  
	    self.payment_type	||= "" 
	    self.sale_date		||= "" 
	    self.user_id		||= 0.0  
	    self.client_id		||= 0.0 
	    self.product_id		  
	    self.commission_id	||= 0.0  
    end
	
	def calculate
		self.subtotal = self.quantity * Product.find(product_id).price
		self.total = (1 + tax / 100) * self.subtotal
		self.commission = self.total * ( Product.find(product_id).commission_rate / 100 )
	end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, success: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        flash.now[:danger] = "There was a problem creating the sale"
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, success: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        flash.now[:danger] = "There was a problem updating the sale"
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, success: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:quantity, :subtotal, :tax, :total, :payment_type, :sale_date, :user_id, :client_id, :commission, :commissions_id, :product_id)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<%= form_for(@sale, :html => {:class => "form-horizontal"}) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% @sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
      <%= f.label 'Sales Person', class:"col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.collection_select :user_id, User.all.where(role: 'Sales').sort_by(&:full_name),:id,:full_name, {include_blank: false}, {class:"form-control"} %>
      </div>
  </div>
  <div class="form-group">
      <%= f.label :client, class:"col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.collection_select :client_id, Client.order(:name).nil? ? "N/A" : Client.order(:name),:id,:name, 
          {include_blank: false}, {class:"form-control"} %>
      </div>
  </div>
   <div class="form-group">
      <%= f.label :product, class:"col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.collection_select :product_id, Product.all,:id,:name_and_price, {include_blank: false}, {class:"form-control"} %>
      </div>
  </div>
  <div class="form-group">
    <%= f.label :quantity, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
    <%= f.number_field :quantity, :value => (number_with_precision(f.object.quantity, :precision => 0) || 0), class: 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :tax, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <div class="input-group">
        <%= f.number_field :tax, :step => 'any', class: 'text_field form-control' %>
        <div class="input-group-addon">%</div>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :payment_type, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
    <%= f.select :payment_type, options_for_select([["Cash", "Cash"], ["Check", "Check"], 
      ["Credit Card", "Credit Card"]]), {}, {include_blank: 'false', class: 'form-control'} %>
    
    </div>
  </div>
  <div class="form-group">
    <%= f.label :sale_date, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
    
    <%= f.datetime_select :sale_date, class: 'form-control' %>
    </div>
  </div>
  <div class="actions pull-right">
    <%= f.submit "Save", class: "btn btn-primary"%>
    <%= link_to 'Cancel', sales_path, class: "btn btn-none" %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Edit Sale
        </h1>
    </div>
</div>

<%= render 'form' %>

app/views/sales/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Sales
        </h1>
    </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Sales Person</th>
      <th>Product</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Total</th>
      <th>Payment type</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.sale_date %></td>
        <td><%= User.find(sale.user_id).nil? ? "N/A" : User.find(sale.user_id).full_name %></td>
        <td><%= Product.find(sale.product_id).nil? ? "N/A" : Product.find(sale.product_id).name %></td>
        <td>$<%= Product.find(sale.product_id).nil? ? "N/A" : Product.find(sale.product_id).price %></td>
        <td><%= sale.quantity %></td>
        <td>$<%= number_with_precision(sale.total, precision:2) %></td>
        <td><%= sale.payment_type %></td>
         <td>
          <%= link_to sale, class: 'btn btn-default btn-xs' do %>
            <i class="fa fa-search" title="View" aria-hidden="true"></i>
          <% end %>
        </td>
        <td>
          <%= link_to edit_sale_path(sale), class: 'btn btn-default btn-xs' do %>
            <i class="fa fa-pencil-square-o" title="Edit" aria-hidden="true"></i>
          <% end %>
        </td>
        <td>
          <%= link_to sale, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' do %>
          <i class="fa fa-trash-o" title="Delete" aria-hidden="true"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_sale_path, class: 'btn btn-primary' do%>
Add
<% end %>

app/views/sales/new.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">
            Add Sale
        </h1>
    </div>
</div>

<%= render 'form' %>

app/views/sales/show.html.erb
<p>
  <strong>Product:</strong>
  <%= Product.joins(:sales).where(id: @sale.product_id).limit(1).pluck(:name).flatten.join('') %>
</p>
<p>
  <strong>Price:</strong>
  $<%= Product.joins(:sales).where(id: @sale.product_id).limit(1).pluck(:price).flatten.join('') %>
</p>
<p>
  <strong>Quantity:</strong>
  <%= @sale.quantity %>
</p>

<p>
  <strong>Subtotal:</strong>
  $<%= number_with_precision(@sale.subtotal, precision:2) %>
</p>

<p>
  <strong>Tax:</strong>
  <%= @sale.tax %>%
</p>

<p>
  <strong>Total:</strong>
  $<%= number_with_precision(@sale.total, precision:2) %>
</p>

<p>
  <strong>Payment type:</strong>
  <%= @sale.payment_type %>
</p>

<p>
  <strong>Sale date:</strong>
  <%= @sale.sale_date %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale), class: "btn btn-primary" %>
<%= link_to 'Back', sales_path, class: "btn btn-none" %>