config/routes.rb
Rails.application.routes.draw do

  root 'home#dashboard'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :products
  resources :commissions
  resources :regions
  resources :sales
  resources :clients

  get 'ranking'  => 'static_pages#ranking'
  get 'dashboard'  => 'home#dashboard'
  
  get '*path' => redirect('/')
  

  get '/rails/info/properties' => "rails/info#properties"
  get '/rails/info/routes'     => "rails/info#routes"
  get '/rails/info'            => "rails/info#index"
end

app/views/layouts/_header.html.erb
<header class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
    <%= link_to 'Sound Sales', dashboard_path, class: "navbar-brand" %>
</header>

app/views/layouts/_shim.html.erb
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

app/views/layouts/_sidebar.html.erb
<div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav side-nav">
        <li>
            <%= link_to dashboard_path do%>
                        <i class="fa fa-fw fa-dashboard"></i> 
                        Dashboard
            <% end %>
        </li>
        <% if current_user.has_role?('Sales') || current_user.has_role?('Admin') %>
            <li>
                <a href="javascript:;" data-toggle="collapse" data-target="#sales"><i class="fa fa-fw fa-line-chart"></i> Sales <i class="fa fa-fw fa-caret-down"></i></a>
                <ul id="sales" class="collapse">
                    <li>
                        <%= link_to new_sale_path do%>
                            Add Sale
                        <% end %>
                    </li>
                    <li>
                        <%= link_to sales_path do%>
                            View Sales
                        <% end %>
                    </li>
                </ul>
            </li>
        <% end %>
        <% if current_user.has_role?('Accounting') || current_user.has_role?('Admin') %>
            <li>
                <a href="javascript:;" data-toggle="collapse" data-target="#products"><i class="fa fa-fw fa-shopping-cart"></i> Products <i class="fa fa-fw fa-caret-down"></i></a>
                <ul id="products" class="collapse">
                    <li>
                        <%= link_to new_product_path do%>
                            Add Product
                        <% end %>
                    </li>
                    <li>
                        <%= link_to products_path do%>
                            View Product
                        <% end %>
                    </li>
                </ul>
            </li>
        <% end %>
        <% if current_user.has_role?('Human Resources') || current_user.has_role?('Admin') %>
            <li>
                <a href="javascript:;" data-toggle="collapse" data-target="#users"><i class="fa fa-fw fa-users"></i> Users <i class="fa fa-fw fa-caret-down"></i></a>
                <ul id="users" class="collapse">
                    <li>
                        <%= link_to new_user_path do%>
                            Add User
                        <% end %>
                    </li>
                    <li>
                        <%= link_to users_path do%>
                            View Users
                        <% end %>
                    </li>
                </ul>
            </li>
        <% end %>
        <% if current_user.has_role?('Accounting') || current_user.has_role?('Admin') || current_user.has_role?('Sales Manager') %>
            <li>
                <a href="javascript:;" data-toggle="collapse" data-target="#regions"><i class="fa fa-fw fa-map-marker"></i> Regions <i class="fa fa-fw fa-caret-down"></i></a>
                <ul id="regions" class="collapse">
                    <li>
                        <%= link_to new_region_path do%>
                            Add Region
                        <% end %>
                    </li>
                    <li>
                        <%= link_to regions_path do%>
                            View Regions
                        <% end %>
                    </li>
                </ul>
            </li>
        <% end %>
        <% if current_user.has_role?('Accounting') || current_user.has_role?('Admin') %>
            <li>
                <a href="javascript:;" data-toggle="collapse" data-target="#clients"><i class="fa fa-fw fa-user"></i> Clients <i class="fa fa-fw fa-caret-down"></i></a>
                <ul id="clients" class="collapse">
                    <li>
                        <%= link_to new_client_path do%>
                            Add Clients
                        <% end %>
                    </li>
                    <li>
                        <%= link_to clients_path do%>
                            View Clients
                        <% end %>
                    </li>
                </ul>
            </li>
        <% end %>
        <% if current_user.has_role?('Sales') || current_user.has_role?('Admin') %>
            <li>
                <%= link_to commissions_path do%>
                    <i class="fa fa-fw fa-dollar"></i> 
                    Commissions
                <% end %>
            </li>
        <% end %>
        <% if current_user.has_role?('Sales') || current_user.has_role?('Admin') %>
            <li>
                <%= link_to ranking_path do%>
                        <i class="fa fa-fw fa-trophy"></i> 
                        Ranking
                    <% end %>
            </li>
        <% end %>
    </ul>
</div>

app/views/layouts/_topbar.html.erb
<ul class="nav navbar-right top-nav">
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
        <ul class="dropdown-menu message-dropdown">
            <li class="message-preview">
                <a href="#">
                    <div class="media">
                        <span class="pull-left">
                            <img class="media-object" src="http://placehold.it/50x50" alt="">
                        </span>
                        <div class="media-body">
                            <h5 class="media-heading">
                                <strong>Keith Fung</strong>
                            </h5>
                            <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 5:01 PM</p>
                            <p>This is so much work! Why did we choose Ruby on Rails?</p>
                        </div>
                    </div>
                </a>
            </li>
            <li class="message-preview">
                <a href="#">
                    <div class="media">
                        <span class="pull-left">
                            <img class="media-object" src="http://placehold.it/50x50" alt="">
                        </span>
                        <div class="media-body">
                            <h5 class="media-heading">
                                <strong>John Hovanec</strong>
                            </h5>
                            <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 7:32 PM</p>
                            <p>Oh the humanity!</p>
                        </div>
                    </div>
                </a>
            </li>
            <li class="message-preview">
                <a href="#">
                    <div class="media">
                        <span class="pull-left">
                            <img class="media-object" src="http://placehold.it/50x50" alt="">
                        </span>
                        <div class="media-body">
                            <h5 class="media-heading">
                                <strong>John Smith</strong>
                            </h5>
                            <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                            <p>Lorem ipsum dolor sit amet, consectetur...</p>
                        </div>
                    </div>
                </a>
            </li>
            <li class="message-footer">
                <a href="#">Read All New Messages</a>
            </li>
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> 
        <% if logged_in? %>
            <%= "#{ current_user.full_name}" %>
        <% else %>
            Not logged in
        <% end %>
        <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li>
            <% if logged_in? %>
                <%= link_to "Log out", logout_path, method: :delete %>
            <% else %>
                <%= link_to "Log in", login_path %>
            <% end %>
            </li>
        </ul>
    </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoundSales</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
<body>
<% if logged_in? %>     
   <div id="wrapper" >
        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <%= render 'layouts/header' %>
            <!-- Top Menu Items -->
            <%= render 'layouts/topbar' %>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <%= render 'layouts/sidebar' %>
            <!-- /.navbar-collapse -->
        </nav>
        
        <div id="page-wrapper">
            <div class="container-fluid fill-height">
                <% flash.each do |message_type, message| %>
                    <div class="alert alert-<%= message_type %>"><%= message %></div>
                <% end %>
                <%= yield %>
            </div>
        </div>
    </div>
    <% else %>
        <div>
         <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <%= render 'layouts/header' %>
        </div>
         <div class="container">
            <div class="row top-buffer">
            <div class="row">
                <div class="col-sm-6 col-md-4 col-md-offset-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <span class="fa fa-lock"></span> Login</div>
                        <div class="panel-body">
                            <% flash.each do |message_type, message| %>
                                <div class="alert alert-<%= message_type %>"><%= message %></div>
                            <% end %>
                            <%= yield %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </div>
    <% end %>  
</body>

</html>